displaymanagers:
  - sddm

defaultDesktopEnvironment:
  executable: "startplasma-x11"
  desktopFile: "plasma.desktop"

basicSetup: false

sysconfigSetup: false

sddm:
  configuration_file: "/etc/sddm.conf.d/kde_settings.conf"
