#!/bin/bash

if ! pkexec /usr/bin/calamares; then
    zenity --error \
        --title="Installer Failed" \
        --text="Calamares failed to start.\nThis ISO may be misconfigured.\n\nPlease rebuild the ISO." \
        --width=300
fi
