#!/bin/bash

export LIBGL_ALWAYS_SOFTWARE=1
/usr/bin/calamares_polkit %f -d -style breeze


if ! pkexec /usr/bin/calamares; then
    zenity --error \
        --title="Installer Failed" \
        --text="Calamares failed to start.\nThis ISO may be misconfigured.\n\nPlease rebuild the ISO." \
        --width=300
fi
